spring:
  profiles:
    active: @profileActive@

---
server:
  port: 8081
  servlet:
    context-path: /spring-demo
spring:
  profiles: dev
  application:
    name: java-best-practices
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://192.168.255.129:3306/SpringBoot
      username: root
      password: root
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

---

server:
  port: 8082
  servlet:
    context-path: /spring-best-practice
spring:
  profiles: test
  application:
    name: java-best-practices
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://192.168.255.129:3306/SpringBoot
      username: root
      password: root
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

---
server:
  port: 8083
  servlet:
    context-path: /spring-best-practice
spring:
  profiles: prod
  application:
    name: java-best-practices
  datasource:
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:p6spy:mysql://192.168.255.129:3306/SpringBoot
      username: root
      password: root
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0