spring:
  profiles:
    active: @profileActive@

---

server:
  port: 8080
  servlet:
    context-path: /spring.cook.com




swagger:
  # 标题
  title: "Spring Boot 使用 Swagger2 构建RESTful API"
  contact:
    # 维护人
    name: "yunlingfly"
    email: "508821881@qq.com"
    url: "https://www.yunlingfly.cn"
  # 版本
  version: "1.0"
  # 描述
  description: "API 描述"
  # swagger扫描的基础包，默认：全扫描
  base-package: "com.dmsdbj.team3.javaprojectbestpractices.controller"
  # 需要处理的基础URL规则，默认：/**
  base-path: "/**"
  license: "Apache License, Version 2.0"
  license-url: "https://www.apache.org/licenses/LICENSE-2.0.html"


spring:
  profiles: dev
  application:
    name: java-best-practices
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/flyway_test
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: root
      password: rootren00.
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
#        wall:
#            enabled: true
       stat:
          enabled: true

  devtools:
    restart:
      enable: true
      additional-paths: src/main

MYENGLISHNAME:
  value: Cook

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

  #flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
  logging:
    level:
      org:
        flywaydb=debug

---

server:
  port: 8081
  servlet:
    context-path: /spring.cook.com

spring:
  profiles: test
  application:
    name: java-best-practices
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/test
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: root
      password: rootren00.
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

---

server:
  port: 8082
  servlet:
    context-path: /spring.cook.com

spring:
  profiles: prod
  application:
    name: java-best-practices
  datasource:
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/test
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      username: root
      password: rootren00.
      db-type: com.alibaba.druid.pool.DruidDataSource
      min-idle: 5
      initial-size: 5
      max-active: 20
      max-wait: 60000
      #      如果当前连接池中某个连接在空闲了timeBetweenEvictionRunsMillis时间后任然没有使用，则被物理性的关闭掉。
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        wall:
        enabled: true
#  devtools:
#    restart:
#      enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dmsdbj.team3.javaprojectbestpractices.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#swagger:
#  title: Best Practices
#  contact:
#    name: sunshine
#    email: 18333640045@163.com
#    url:
#  version: 1.0.1
#  description: SSM project best practices
#  base-package: com.dmsdbj.team3.javaprojectbestpractices.controller
#  base-path: /**
#  license: "许可证"
# spring-actuator
info:
  app:
    name: spring-boot-starter-actuator
  version: 1.0.0
  test: test



management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


# promethues
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}



